# site settings
title: ARCADE
logo: images/logo_whitetext.svg

# page defaults
description: Advaned Robotics and Computationally AugmenteD Environments
header: images/header.jpg
footer: images/footer.jpg

# site nav bar
nav:
  - link: research
    tooltip: Published works
  - link: resources
    tooltip: Tools, datasets, and more
  - link: team
    tooltip: About our team
  - link: blog
    tooltip: Musings and announcements
  - link: contact
    tooltip: Email, address, and location

# site social media
email: unberath@jhu.edu
google-scholar: 1bd5mdIAAAAJ
github: arcadelab
twitter: MathiasUnberath
# instagram: YourLabHandle
# youtube: YourLabChannel

# base directory where site is hosted
baseurl: ""

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
